### ISSUE TITLE
push method does not work when extends from  Array

### ISSUE THREAD

**Issue by slashhuang** [renaesop/simple-promise#2]
class NextObjectArray extends Array{
  constructor(ctx) {
    super();
    // if (ctx instanceof Promise) this._ctx = ctx;
  }
  push(...args) {    super.push(...args);
    this._ctx && this._ctx._checkState();
  }
}

**Comment by renaesop** [comment]
when it happens?

**Comment by renaesop** [comment]
es2015的class extends没法完美转换为e5，已移除使用继承的部分。
